### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by b3457m0d3** [ayltai/Android-Lib-Pen#1]
Is there a way this could be used with phonegap?

**Comment by ayltai** [comment]
Yes, this is possible by implementing a user-defined PhoneGap plugin. However, targeting a very limited number of phone models from only one brand (Samsung) defeats the major advantage of PhoneGap.

**Comment by b3457m0d3** [comment]
Thank you.  This is very true.  I have 2 note devices and my team uses them as well.  I am interested in using this for in-house dev tools.

**Comment by b3457m0d3** [comment]
Do you plan on documenting your api?

**Comment by ayltai** [comment]
I'm in the process of upgrading the API to use the latest Pen SDK (1.5.0 beta1), and add a demo project with documentation. But I do not plan to wrap all the features that the original SDK provides (e.g. add EditText object to canvas) as I don't find it useful for myself. It's not hard to do it though.

**Comment by b3457m0d3** [comment]
Thats awesome.  Thank you much for your generous offering to this community.  I am working on a scrapbooking app for a friend and your code covers most of the features I planned to use!  I look forward to having an example to toy with.  Stay awesome.
